# frozen_string_literal: true

module StorageTables
  module Attachable
    module Changes
      # Helper methods for attachable changes.
      module Helper
        def extract_filename(attachable)
          case attachable
          when ActionDispatch::Http::UploadedFile, Rack::Test::UploadedFile
            attachable.original_filename
          when Pathname
            attachable.basename.to_s
          when Hash
            attachable.fetch(:filename)
          when ActiveStorage::Blob
            attachable.filename.to_s
          when File
            File.basename(attachable.path)
          end
        end

        # Extra columns to set on the attachment record itself, rather than on the blob.
        #
        # Only a Hash attachable can carry them: the setter generated by `has_one_stored` is reached
        # through `assign_attributes`, which passes a single argument, so there is nowhere else to
        # put them.
        #
        #   record.document = { io:, filename:, attachment_attributes: { template_name: "invoice" } }
        def extract_attachment_attributes(attachable)
          return {} unless attachable.is_a?(Hash)

          attachable.fetch(:attachment_attributes, {})
        end

        # Uploads the attachable to the blob.
        def upload(attachable, blob)
          if ActiveRecord::Base.connection.open_transactions > MAX_TRANSACTIONS_OPEN
            raise StorageTables::ActiveRecordError, "Cannot upload a blob inside a transaction"
          end

          case attachable
          when ActionDispatch::Http::UploadedFile, Pathname
            blob.upload_without_unfurling(attachable.open)
          when Rack::Test::UploadedFile
            blob.upload_without_unfurling(
              attachable.respond_to?(:open) ? attachable.open : attachable
            )
          when Hash
            blob.upload_without_unfurling(attachable.fetch(:io))
          when File
            blob.upload_without_unfurling(attachable)
          when ActiveStorage::Blob
            blob.upload_without_unfurling(StringIO.new(attachable.download))
          end
        rescue StandardError
          blob.destroy!
          raise
        end
      end
    end
  end
end
